### ISSUE TITLE
能更改README吗

### ISSUE THREAD

**Issue by Voidlink132** [SweelLong/PhigrosCrossPlatformDataMigrator#1]
给star了，但是我真的很想知道苹果转安卓怎么操作
于是rt，请更改readme

**Comment by SweelLong** [comment]
实际上苹果转安卓就是一个逆向的过程，
看过ReadMe就会知道，imazingapp这个文件
具体步骤如下：
备份一下获取苹果端的imazingapp然后用解压工具打开提取存档工具games.Pigeon.Phigros.plist
用工具【2】模式，获取安卓存档，然后用模拟器存入覆盖即可
---
当然如果你真的需要和安卓转苹果一样详细的步骤的话，请告知，这需要一点时间...

**Comment by SweelLong** [comment]
不过忘记更新最新版的链接了
在这里https://github.com/SweelLong/PhigrosCrossPlatformDataMigrator/releases/tag/v2.0.0.0

**Comment by SweelLong** [comment]
如果还是需要教程的话，回复一下，我晚点制作一下

**Comment by Voidlink132** [comment]
好的谢谢了
love from china

**Comment by SweelLong** [comment]
https://github.com/SweelLong/PhigrosCrossPlatformDataMigrator/blob/main/README.md#%E8%8B%B9%E6%9E%9C%E7%AB%AF%E8%BD%AC%E5%9B%9E%E5%AE%89%E5%8D%93%E7%AB%AF%E8%BF%9B%E8%A1%8C%E4%BA%91%E5%AD%98%E6%A1%A3%E7%9A%84%E9%80%86%E5%90%91%E6%93%8D%E4%BD%9C

**Comment by SweelLong** [comment]
https://github.com/SweelLong/PhigrosCrossPlatformDataMigrator?tab=readme-ov-file#%E8%8B%B9%E6%9E%9C%E7%AB%AF%E8%BD%AC%E5%9B%9E%E5%AE%89%E5%8D%93%E7%AB%AF%E8%BF%9B%E8%A1%8C%E4%BA%91%E5%AD%98%E6%A1%A3%E7%9A%84%E9%80%86%E5%90%91%E6%93%8D%E4%BD%9C

**Comment by Voidlink132** [comment]
对不起打扰到您，但是我的xml文件似乎说这需要升级了，可能是因为更新了3.8.0版本罢：
<map>
<int name="NeedUpdateSongsData" value="4"/>
<int name="setDspBuffer" value="1"/>
</map>

**Comment by UT-player-92** [comment]
<map>
<int name="NeedUpdateSongsData" value="4"/>
<int name="setDspBuffer" value="1"/>
</map>

**Comment by UT-player-92** [comment]
【map>
<int name="NeedUpdateSongsData" value="4"/>
<int name="setDspBuffer" value="1"/>
</map】

**Comment by Voidlink132** [comment]
map
int name="NeedUpdateSongsData" value="4"
int name="setDspBuffer" value="1"
map
尖括号全删了以防被吞

**Comment by SweelLong** [comment]
实际上，phigros不是要恢复云存档的功能了吗

**Comment by SweelLong** [comment]
以及我就是3.8.0操作的，如果你急用可以发个qq到我邮箱

**Comment by Voidlink132** [comment]
急着和群u吹水（
好吧先让我自己研究一下

**Comment by SweelLong** [comment]
实际上，phigros不是要[恢复云存档的功能](https://www.bilibili.com/opus/962084704525222003?spm_id_from=333.999.0.0)了吗
《Phigros将于2024年8月16日更新》
以及我就是3.8.0操作的，如果你急用可以发个qq号码到我邮箱sweellong@qq.com，我帮你看看

**Comment by Voidlink132** [comment]
好吧我真不会了对不起啊麻烦你了

在 2024-08-13 22:15:41，SweelLong ***@***.***> 写道：


实际上，phigros不是要恢复云存档的功能了吗
《Phigros将于2024年8月16日更新》
***@***.***，我帮你看看

**Comment by Voidlink132** [comment]
![屏幕截图 2024-08-13 233141](https://github.com/user-attachments/assets/6c9b808e-e1d8-40c8-9cb1-a00b81f48296)
转移过后的只有1kb捏
